In [1]:
import pandas as pd
df=pd.read_csv('orders_practice.csv')
display(df.head())
display(df.tail())

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
0,SP100000,Isha Singh,Male,58.0,Mumbai,2025-09-12,Laptop,4,55000,220000,UPI,1.0
1,SP100001,Dev Kulkarni,Female,55.0,Bengaluru,2025-02-16,Mouse,5,600,3000,Net Banking,3.5
2,SP100002,Sneha Iyer,Female,48.0,Delhi,2025-10-28,Mouse,2,600,1200,Cash,3.5
3,SP100003,Priya Verma,Female,19.0,Nashik,2025-10-30,Keyboard,2,1200,2400,Card,4.0
4,SP100004,Dev Nair,Male,64.0,Delhi,2025-11-22,Phone,4,22000,88000,Cash,4.5

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
195,SP100195,Priya Singh,Female,36.0,Bengaluru,2025-07-14,Charger,4,900,3600,Cash,2.0
196,SP100196,Rohan Gupta,Female,53.0,NaN,2025-06-21,Webcam,5,2200,11000,Net Banking,2.0
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0
199,SP100199,Anjali Joshi,Female,16.0,Bengaluru,2025-12-29,Mouse,3,600,1800,Card,2.0

In [2]:
print(df.columns)

Index(['Order ID', 'Customer Name', 'Gender', 'Age', 'City', 'Order Date',
       'Product', 'Qty', 'Unit Price', 'Total Amount', 'Payment Mode',
       'Rating'],
      dtype='str')

In [3]:
products=df['Product']
products

0        Laptop
1         Mouse
2         Mouse
3      Keyboard
4         Phone
         ...
195     Charger
196      Webcam
197      Webcam
198     Monitor
199       Mouse
Name: Product, Length: 200, dtype: str

In [4]:
cust_city=df[['Customer Name','City']]
cust_city

      Customer Name       City
0        Isha Singh     Mumbai
1      Dev Kulkarni  Bengaluru
2        Sneha Iyer      Delhi
3       Priya Verma     Nashik
4          Dev Nair      Delhi
..              ...        ...
195     Priya Singh  Bengaluru
196     Rohan Gupta        NaN
197       Isha Nair     Nashik
198  Priya Kulkarni    Chennai
199    Anjali Joshi  Bengaluru

[200 rows x 2 columns]

In [5]:
df.columns

Index(['Order ID', 'Customer Name', 'Gender', 'Age', 'City', 'Order Date',
       'Product', 'Qty', 'Unit Price', 'Total Amount', 'Payment Mode',
       'Rating'],
      dtype='str')

In [6]:
Sales_info=df[['Qty','Total Amount']]
Sales_info

     Qty  Total Amount
0      4        220000
1      5          3000
2      2          1200
3      2          2400
4      4         88000
..   ...           ...
195    4          3600
196    5         11000
197    5         11000
198    4         36000
199    3          1800

[200 rows x 2 columns]